sudo: required
services: 
  - docker
before_install:
  - docker build -t imspr336/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run imspr336/react-test echo Done
after_success:
  - docker build -t imspr336/multi-client ./client
  - docker build -t imspr336/multi-nginx ./nginx
  - docker build -t imspr336/multi-server ./server
  - docker build -t imspr336/multi-worker ./worker
# Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push imspr336/multi-client
  - docker push imspr336/multi-server
  - docker push imspr336/multi-nginx
  - docker push imspr336/multi-worker

# Push images to docker hub


